<a href="https://colab.research.google.com/github/menalipaul2503/class/blob/main/numpyPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# first import the numpy library to use it :
import numpy as np
arr1=[23,432,23,4,7];
i=0
while(i<5):
  int(arr1[i])
  print("arr1",type(arr1[i]))
  i=i+1;
numpyarr=np.array(arr1);

i=0;
while(i<5):
  print(type(numpyarr[i]))
  i=i+1;


arr1 <class 'int'>
arr1 <class 'int'>
arr1 <class 'int'>
arr1 <class 'int'>
arr1 <class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
# creating a 2d numpy array :
import numpy as np
arr2=np.array([[3,45,56,4],[3,5,3,5]])
print(arr2)
i=0
while (i<2):
  j=0
  while(j<4):
    print(arr2[i][j],type(arr2[i][j]))
    j+=1;
  i+=1  


[[ 3 45 56  4]
 [ 3  5  3  5]]
3 <class 'numpy.int64'>
45 <class 'numpy.int64'>
56 <class 'numpy.int64'>
4 <class 'numpy.int64'>
3 <class 'numpy.int64'>
5 <class 'numpy.int64'>
3 <class 'numpy.int64'>
5 <class 'numpy.int64'>


In [ ]:
# create 2 x 4 matrix
matrix=np.array([[1,23,4,5],[1,23,4,5]])
print(matrix)

[[ 1 23  4  5]
 [ 1 23  4  5]]


In [ ]:
# using functions of numpy library 
# rand()uses to generte random numbers and store it in the array :
print("rand(): 1D")
randarr=np.random.rand(4)
print(randarr)
# creating a 2D arrar of random genearted numbers :
print("rand(): 2D")
randarr=np.random.rand(3,3)
print(randarr)
# using randint(): use to generate random interger number  required to give range of the number as the  parameter   ;
print("randint : 1D")
randintarr=np.random.randint(0,100)
print(randintarr)
# randint(): it can be use to generate random number of int array also with 3 parameter (lower bound ,uppper bound,size ):
print("randintarray :")
randintarr1D=np.random.randint(0,100,3)
print(randintarr1D)
# numpy arange(): use to create a array of evenely distributed numbers of array and take range and  difference  as parmater where range is mendatory and difference is by defual 1 and not required every tikme as a parameter (lowerbound, upperbound,difference );
print("generating a sequence of number with arange")
range=np.arange(1,10,3) 
print(range)
# numpy matrix design;
# eye() : it is use to design in the matrix format where size of the matrix is given as the paramter :
print("numpy matrix designing  :")
y=np.eye(7);
print(y)
print("numpy matrix designing  :")
y=np.eye(7,7);
print(y)
# creating numpy array of complete zeros np.zeros() :
print("numpy matrix designing  :")
zero=np.zeros(7);
print(zero)


rand(): 1D
[0.88267968 0.34118353 0.0616847  0.88349932]
rand(): 2D
[[0.18644293 0.14444949 0.14363542]
 [0.2257832  0.74085368 0.6106324 ]
 [0.35101688 0.93051912 0.66102832]]
randint : 1D
34
randintarray :
[34 69 13]
generating a sequence of number with arange
[1 4 7]
numpy matrix designing  :
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
numpy matrix designing  :
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
numpy matrix designing  :
[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# challege taking a number  x as input and then genrating  a marix of 1 x 10 ranging the number from 0 to x:
x=int(input("enter a number :"))
matrix = np.random.randint(1,x,10)
print(matrix)

enter a number :100
[94 66 97 12 57 65 11 73 24 23]


In [ ]:
# adding 2 array in numpy :
x=np.arange(1,20,2)#generaating a a 1D array in range 
y=np.arange(1,20,2)#generaating a a 1D array in range
print("x",x)
print("y",y)
sum=x+y
print("x+y",sum) 
# sqare of all elements in sum array :
square  = sum**2
print("square :")
print(square)
# square root of the array of square :
sqrt  = np.sqrt(square)
print("square root :")
print(sqrt)


x [ 1  3  5  7  9 11 13 15 17 19]
y [ 1  3  5  7  9 11 13 15 17 19]
x+y [ 2  6 10 14 18 22 26 30 34 38]
square :
[   4   36  100  196  324  484  676  900 1156 1444]
square root :
[ 2.  6. 10. 14. 18. 22. 26. 30. 34. 38.]


In [ ]:
# challenge find the difference between 2 array :
print("arr1 :")
arr1=np.array ([2,35,675,214,46,66,65])
print("arr2 :")
arr2=np.array ([1,34,5,23,4,543,3])
dif=arr1-arr2
print("diff :")
print(dif)


arr1 :
arr2 :
diff :
[   1    1  670  191   42 -477   62]


In [ ]:
# slicing array and indexing :

dummyarr=np.array([1,2,3,4,5,6,7,8,9])

print("array :")
print(dummyarr)
# access the elemnt by the  indexs 
print("array [1]:",dummyarr[1])
print("array [8]",dummyarr[-1])
# accessing elements by slicing :
print("array [1,8]",dummyarr[1:-1])
print("array[1,6]",dummyarr[2:7])
# changing array elements value in array :
dummyarr[1]=23;
dummyarr[-1]=34;
print("after changing values")
print(dummyarr)
print("after slicing  changing values")
dummyarr[0:4]=9
print(dummyarr)
# performing function on 2D array :
# generated  elemnts of matrix :
dummyarr2D=np.random.randint(1,10,(4,4))
# access the elments :
print("original array :")
print(dummyarr2D)
print("array [0][3]:",dummyarr2D[0][3]);

print("access the array first row :")
print(dummyarr2D[0])
print("access the array last row :")
print(dummyarr2D[-1])

array :
[1 2 3 4 5 6 7 8 9]
array [1]: 2
array [8] 9
array [1,8] [2 3 4 5 6 7 8]
array[1,6] [3 4 5 6 7]
after changing values
[ 1 23  3  4  5  6  7  8 34]
after slicing  changing values
[ 9  9  9  9  5  6  7  8 34]
original array :
[[9 7 9 6]
 [5 5 1 1]
 [3 8 2 4]
 [1 2 7 6]]
array [0][3]: 6
access the array first row :
[9 7 9 6]
access the array last row :
[1 2 7 6]


In [ ]:
# challenge create a random generated array of 5x5 matrix  and then make its lasst row  all elemt=ent 0 :
matrix2 = np.random.randint(1,10,(5,5))
print("original matrix :\n",matrix2)
matrix2[-1]=0
print("after update :\n",matrix2)

original matrix :
 [[6 6 6 2 6]
 [7 2 6 8 4]
 [1 3 7 2 4]
 [3 1 3 9 7]
 [3 6 5 3 3]]
after update :
 [[6 6 6 2 6]
 [7 2 6 8 4]
 [1 3 7 2 4]
 [3 1 3 9 7]
 [0 0 0 0 0]]


In [ ]:
# numpy conditionals :
# filtering array in numpy :
genmatrix = np.random.randint(1,10,(5,5));
print("original matrix :",genmatrix)
newmatrix = genmatrix[genmatrix < 7]
print(newmatrix)
# obtaining only odd elements in an array :
print("odd elements :")
oddmatrix = genmatrix[genmatrix%2 == 1]
print(oddmatrix)
# obtaining only even elements in an array :
print("even  elements :") 
evenmatrix = genmatrix[genmatrix%2 == 0]
print(evenmatrix)



original matrix : [[4 6 7 8 9]
 [7 7 8 5 1]
 [4 5 1 8 8]
 [4 3 6 7 7]
 [5 6 9 6 2]]
[4 6 5 1 4 5 1 4 3 6 5 6 6 2]
odd elements :
[7 9 7 7 5 1 5 1 3 7 7 5 9]
even  elements :
[4 6 8 8 4 8 8 4 6 6 6 2]


In [ ]:
# challenge replace all negative elements of the array with 0 and odd to -2:
mat=np.array([[2,30,20,-4,-2],[3,4,40,-3,2],[-3,4,-6,90,10],[25,35,34,22,12],[13,24,22,32,37]])
print("original matrix :")
print(mat)
mat[mat<0]=0
mat[mat%2==1]=-2
print("updated matrix :")
print(mat)

original matrix :
[[ 2 30 20 -4 -2]
 [ 3  4 40 -3  2]
 [-3  4 -6 90 10]
 [25 35 34 22 12]
 [13 24 22 32 37]]
updated matrix :
[[ 2 30 20  0  0]
 [-2  4 40  0  2]
 [ 0  4  0 90 10]
 [-2 -2 34 22 12]
 [-2 24 22 32 -2]]
